### ISSUE TITLE
Missing Resurrect 'Ems

### ISSUE THREAD

**Issue by CakeLancelot** [OpenFusionProject/tabledata#6]
**Overworld:**
~~Pokey Oaks Gazebo~~
~~Malph's~~
~~South of Endsville~~
~~South of Fireswamps~~

**Infected Zones:**
~~Cuts and Bruises Skatepark~~
~~Pokey Oaks Highschool~~
~~Mandark's House~~
~~Megas' Last Stand~~
~~Reactor Works~~
~~Charles Darwin School~~
~~The Canopy~~
~~Dizzy World~~
~~The Fissure~~

**Comment by CakeLancelot** [comment]
Most are fixed by c77e753, but I'll leave this open just in case

**Comment by CakeLancelot** [comment]
Found one missing south of Endsville:
![image](https://user-images.githubusercontent.com/5341136/97633859-bdb5d800-1a02-11eb-81b0-aefc92b61c5c.png)

**Comment by CakeLancelot** [comment]
![image](https://user-images.githubusercontent.com/5341136/98065392-2396cb00-1e1a-11eb-8a34-bf99d2b3eac6.png)
Another one at the southern part of FireSwamps

**Comment by dongresource** [comment]
Added the last three missing Resurrect 'Ems in 75d82f3155687d73ad72cfc479d2c2c7c3ecd20f.

That should be all of them, so I'm closing the issue.
